spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:9013}/${DB_NAME:goggles}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-address : false
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL1:localhost}:9001/eureka/,http://${EUREKA_SERVER_URL2:localhost}:9002/eureka/