CREATE TABLE p_user (
    user_id         VARCHAR(36)  NOT NULL,
    email           VARCHAR(255) NOT NULL,
    name            VARCHAR(20)  NOT NULL,
    nick_name       VARCHAR(15)  NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    gender          VARCHAR(10),
    birth_date      DATE         NOT NULL,
    phone_number    VARCHAR(20)  NOT NULL,
    personal_consent  BOOLEAN    NOT NULL DEFAULT FALSE,
    marketing_consent BOOLEAN    NOT NULL DEFAULT FALSE,
    email_consent     BOOLEAN    NOT NULL DEFAULT FALSE,
    interests       JSONB,
    jobs            JSONB,
    educations      JSONB,
    majors          JSONB,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    deleted_at      TIMESTAMP,

    CONSTRAINT pk_p_user PRIMARY KEY (user_id),
    CONSTRAINT uq_p_user_email UNIQUE (email),
    CONSTRAINT uq_p_user_nick_name UNIQUE (nick_name),
    CONSTRAINT uq_p_user_phone_number UNIQUE (phone_number),
    CONSTRAINT chk_p_user_role CHECK (role IN ('STUDENT', 'INSTRUCTOR', 'MASTER')),
    CONSTRAINT chk_p_user_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED')),
    CONSTRAINT chk_p_user_gender CHECK (gender IN ('MALE', 'FEMALE'))
);